package com.farmer.be.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DiagnosticTestReportAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosticTestReportAllPropertiesEquals(DiagnosticTestReport expected, DiagnosticTestReport actual) {
        assertDiagnosticTestReportAutoGeneratedPropertiesEquals(expected, actual);
        assertDiagnosticTestReportAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosticTestReportAllUpdatablePropertiesEquals(DiagnosticTestReport expected, DiagnosticTestReport actual) {
        assertDiagnosticTestReportUpdatableFieldsEquals(expected, actual);
        assertDiagnosticTestReportUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosticTestReportAutoGeneratedPropertiesEquals(DiagnosticTestReport expected, DiagnosticTestReport actual) {
        assertThat(actual)
            .as("Verify DiagnosticTestReport auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosticTestReportUpdatableFieldsEquals(DiagnosticTestReport expected, DiagnosticTestReport actual) {
        assertThat(actual)
            .as("Verify DiagnosticTestReport relevant properties")
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getSignedBy()).as("check signedBy").isEqualTo(expected.getSignedBy()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedOn()).as("check createdOn").isEqualTo(expected.getCreatedOn()))
            .satisfies(a -> assertThat(a.getUpdatedBy()).as("check updatedBy").isEqualTo(expected.getUpdatedBy()))
            .satisfies(a -> assertThat(a.getUpdatedOn()).as("check updatedOn").isEqualTo(expected.getUpdatedOn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosticTestReportUpdatableRelationshipsEquals(DiagnosticTestReport expected, DiagnosticTestReport actual) {
        assertThat(actual)
            .as("Verify DiagnosticTestReport relationships")
            .satisfies(a -> assertThat(a.getPatient()).as("check patient").isEqualTo(expected.getPatient()))
            .satisfies(a -> assertThat(a.getTest()).as("check test").isEqualTo(expected.getTest()))
            .satisfies(a -> assertThat(a.getAdmissions()).as("check admissions").isEqualTo(expected.getAdmissions()));
    }
}
